# Generated by Django 6.0.6 on 2026-06-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('birth_place', models.CharField(max_length=150, verbose_name='Lieu de naissance')),
                ('ufr', models.CharField(max_length=150, verbose_name='UFR')),
                ('department', models.CharField(max_length=150, verbose_name='Département')),
                ('program', models.CharField(max_length=150, verbose_name='Filière')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat')], max_length=2, verbose_name='Niveau')),
                ('permanent_code', models.CharField(max_length=50, unique=True, verbose_name='Code permanent')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Photo')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('is_active', models.BooleanField(default=True, verbose_name='Membre actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
