# Generated by Django 6.0.6 on 2026-06-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_resident',
            field=models.BooleanField(default=False, verbose_name='Étudiant résident'),
        ),
    ]
