# Generated by Django 6.0.6 on 2026-06-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('GRADUATED', 'Diplômé'), ('DROPPED', 'Abandon')], default='ACTIVE', max_length=20, verbose_name='Statut universitaire'),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'entrée à l'UADB"),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du tuteur'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du tuteur'),
        ),
        migrations.AddField(
            model_name='student',
            name='home_commune',
            field=models.CharField(blank=True, max_length=100, verbose_name="Commune d'origine"),
        ),
        migrations.AddField(
            model_name='student',
            name='home_department',
            field=models.CharField(blank=True, max_length=100, verbose_name="Département d'origine"),
        ),
    ]
