# Generated by Django 6.0.6 on 2026-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_academic_status_student_entry_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du tuteur'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du tuteur'),
        ),
    ]
